import json
import os
import random
from pathlib import Path
from tarfile import TarFile
from typing import List
from zipfile import ZipFile

import datasets
import requests
from datasets import (
    BuilderConfig,
    DatasetInfo,
    Features,
    GeneratorBasedBuilder,
    Split,
    SplitGenerator,
    Value,
    Version,
)
from kss import Kss
from natsort import natsorted
from tqdm import tqdm


_LICENSE = """
AI 데이터 허브에서 제공되는 인공지능 학습용 데이터(이하 ‘AI데이터’라고 함)는 과학기술정보통신부와 한국지능정보사회진흥원의 「지능정보산업 인프라 조성」 사업의 일환으로 구축되었으며, 본 사업의 유‧무형적 결과물인 데이터, AI응용모델 및 데이터 저작도구의 소스, 각종 매뉴얼 등(이하 ‘AI데이터 등’)에 대한 일체의 권리는 AI데이터 등의 구축 수행기관 및 참여기관(이하 ‘수행기관 등’)과 한국지능정보사회진흥원에 있습니다.

본 AI 데이터는 인공지능 학습모델의 학습용으로만 사용할 수 있습니다. 다만 기존의 데이터셋을 활용하시어 만들어진 2차 저작물(훈련으로 만들어진 지능형 제품・서비스, 챗봇 등) 은 영리적・비영리적 활용이 가능합니다.
"""

_DESCRIPTION = """지문-질문-답변으로 구성된 약 40만 건의 데이터셋으로 수식은 LaTex을, 표는 html 문법을 이용하고 동의 질문을 함께 구축함. ‘정답경계추출형’, ‘YesNo 단문형’, ‘표 정답 추출형’, ‘다지선다형’, ‘절차형’ 5가지로 구분"""

DATASET_KEY = "71533"
DOWNLOAD_URL = f"https://api.aihub.or.kr/down/{DATASET_KEY}.do"
_HOMEPAGE = (
    f"https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn={DATASET_KEY}"
)
_VERSION = Version("1.1.0")
_DATANAME = "TechnologyScienceDocumentMachineReadingComprehensionAITrainingDataset"
DATASET_SIZE = 0.09085

kdc_dict = {
    "000": "총류",
    "010": "도서학, 서지학",
    "020": "문헌정보학",
    "030": "백과사전",
    "040": "강연집, 수필집, 연설문집",
    "001": "지식 및 학문 일반",
    "003": "이론 체계 및 시스템",
    "004": "컴퓨터과학",
    "005": "프로그래밍, 프로그램, 데이터",
    "006": "[미사용]",
    "007": "[미사용]",
    "008": "[미사용]",
    "009": "[미사용]",
    "011": "저작",
    "012": "필사본, 판본, 제본",
    "013": "출판 및 판매",
    "014": "개인서지 및 목록",
    "015": "국가별 서지 및 목록",
    "016": "주제별 서지 및 목록",
    "017": "특수서지 및 목록",
    "018": "일반서지 및 목록",
    "019": "장서목록",
    "021": "도서관 행정 및 재정",
    "022": "도서관 건축 및 설비",
    "023": "도서관 경영, 관리",
    "024": "수서, 정리 및 보존",
    "025": "도서관 봉사 및 활동",
    "026": "일반도서관",
    "027": "학교 및 대학 도서관",
    "028": "기록관리",
    "029": "독서 및 정보매체의 이용",
    "031": "한국어",
    "032": "중국어",
    "033": "일본어",
    "034": "영어",
    "035": "독일어",
    "036": "프랑스어",
    "037": "스페인어",
    "038": "이탈리아어",
    "039": "기타 제언어",
    "041": "한국어",
    "042": "중국어",
    "043": "일본어",
    "044": "영어",
    "045": "독일어",
    "046": "프랑스어",
    "047": "스페인어",
    "048": "이탈리아어",
    "049": "기타 제언어",
    "050": "일반연속간행물",
    "060": "일반 학회, 단체, 협회, 기관, 연구기관",
    "070": "신문, 저널리즘",
    "080": "일반 전집, 총서",
    "090": "향토자료",
    "051": "한국어",
    "052": "중국어",
    "053": "일본어",
    "054": "영어",
    "055": "독일어",
    "056": "프랑스어",
    "057": "스페인어",
    "058": "기타 제언어",
    "059": "연감",
    "061": "아시아",
    "062": "유럽",
    "063": "아프리카",
    "064": "북아메리카",
    "065": "남아메리카",
    "066": "오세아니야, 양극지방",
    "067": "일반지역",
    "068": "해양",
    "069": "박물관학",
    "071": "아시아",
    "072": "유럽",
    "073": "아프리카",
    "074": "북아메리카",
    "075": "남아메리카",
    "076": "오세아니아, 양극지방",
    "077": "일반지역",
    "078": "특정주제의 신문",
    "079": "[미사용]",
    "081": "개인의 일반전집",
    "082": "2인 이상의 일반 전집, 총서",
    "083": "[미사용]",
    "084": "[미사용]",
    "085": "[미사용]",
    "086": "[미사용]",
    "087": "[미사용]",
    "088": "[미사용]",
    "089": "[미사용]",
    "091": "[미사용]",
    "092": "[미사용]",
    "093": "[미사용]",
    "094": "[미사용]",
    "095": "[미사용]",
    "096": "[미사용]",
    "097": "[미사용]",
    "098": "[미사용]",
    "099": "[미사용]",
    "100": "철학",
    "110": "형이상학",
    "120": "인식론, 인과론, 인간학",
    "130": "철학의 체계",
    "140": "경학",
    "101": "철학 및 이론의 효용",
    "102": "잡저",
    "103": "사전(辭典), 사전(事典), 용어사전",
    "104": "강연집, 수필집",
    "105": "연속간행물",
    "106": "학회, 단체, 협회, 기관, 회의",
    "107": "지도법, 연구법 및 교육, 교육자료",
    "108": "총서, 전집, 선집",
    "109": "철학사",
    "111": "방법론",
    "112": "존재론",
    "113": "우주론 및 자연철학",
    "114": "공간",
    "115": "시간",
    "116": "운동과 변화",
    "117": "구조",
    "118": "힘과 에너지",
    "119": "물질과 질량",
    "121": "인식론",
    "122": "인과론",
    "123": "자유 및 필연",
    "124": "목적론",
    "125": "가치론",
    "126": "철학적 인간학",
    "127": "[미사용]",
    "128": "[미사용]",
    "129": "[미사용]",
    "131": "관념론 및 연관철학",
    "132": "비판철학",
    "133": "합리론",
    "134": "인문주의",
    "135": "경험론",
    "136": "자연주의",
    "137": "유물론",
    "138": "과학주의",
    "139": "기타",
    "141": "역류(한역)",
    "142": "서류",
    "143": "시류",
    "144": "예류",
    "145": "악류",
    "146": "춘추류",
    "147": "효경",
    "148": "사서",
    "149": "[미사용]",
    "150": "동양철학, 동양사상",
    "160": "서양철학",
    "170": "논리학",
    "180": "심리학",
    "190": "윤리학, 도덕철학",
    "151": "한국 철학, 사상",
    "152": "중국 철학, 사상",
    "153": "일본 철학, 사상",
    "154": "동남아시아 제국 철학, 사상",
    "155": "인도 철학, 사상",
    "156": "중앙아시아 제국 철학, 사상",
    "157": "시베리아 철학, 사상",
    "158": "서남아시아 제국 철학, 사상",
    "159": "아라비아반도 철학, 사상",
    "161": "[미사용]",
    "162": "미국철학",
    "163": "북구철학",
    "164": "영국철학",
    "165": "독일, 오스트리아 철학",
    "166": "프랑스, 네덜란드 철학",
    "167": "스페인철학",
    "168": "이탈리아철학",
    "169": "러시아철학",
    "171": "연역법",
    "172": "귀납법",
    "173": "번증법적 논리학",
    "174": "기호, 수리 논리학",
    "175": "오류",
    "176": "삼단논법",
    "177": "가설, 가정",
    "178": "유추",
    "179": "논증, 설득",
    "181": "심리학각론",
    "182": "차이심리학",
    "183": "발달심리학",
    "184": "이상심리학",
    "185": "생리심리학",
    "186": "임상심리학",
    "187": "심령연구 및 비학, 초심리학",
    "188": "상법, 운명판단",
    "189": "응용심리학 일반",
    "191": "일반윤리학 각론",
    "192": "가정윤리",
    "193": "국가 및 정치윤리",
    "194": "사회윤리",
    "195": "직업윤리 일반",
    "196": "오락 및 경기윤리",
    "197": "성윤리 및 생식윤리",
    "198": "소비윤리",
    "199": "도덕훈, 교훈",
    "200": "종교",
    "210": "비교종교",
    "220": "불교",
    "230": "기독교",
    "240": "도교",
    "201": "종교철학 및 종교사상",
    "202": "잡저",
    "203": "사전(辭典), 사전(事典)",
    "204": "자연종교, 자연신학",
    "205": "연속간행물",
    "206": "학회, 단체, 협회, 기관, 회의",
    "207": "지도법, 연구법 및 교육, 교육자료",
    "208": "총서, 전집, 선집",
    "209": "종교사",
    "211": "교리",
    "212": "종교창시자(교주) 및 제자",
    "213": "경전, 성전",
    "214": "종교신앙, 신앙록, 신앙활동, 수도생활",
    "215": "선교, 포교, 전도, 교육활동",
    "216": "종단, 교단(교당론)",
    "217": "예배형식, 의식, 의례",
    "218": "종파, 교파",
    "219": "신화, 신화학",
    "221": "불교교리",
    "222": "부처, 보살, 불제자",
    "223": "경전(불전, 불경, 대장경)",
    "224": "종교신앙, 신앙록, 신앙생활",
    "225": "포교, 교육, 교화활동",
    "226": "사원론",
    "227": "법회, 의식, 행사(의궤)",
    "228": "종파",
    "229": "라마교",
    "231": "기독교신학, 교의학(조직신학)",
    "232": "예수 그리스도, 사도",
    "233": "성서(성경)",
    "234": "종교신앙, 신앙록, 신앙생활",
    "235": "전도, 교육, 교화 활동, 목회학",
    "236": "교회론",
    "237": "예배, 의식, 성례",
    "238": "교파",
    "239": "유대교(유태교)",
    "241": "교의, 신선사상",
    "242": "교주, 개조(장도릉)",
    "243": "도장",
    "244": "신앙록, 신앙생활",
    "245": "포교, 전도, 교육, 교육 활동",
    "246": "사원론(도관)",
    "247": "행사, 법술",
    "248": "교파",
    "249": "[미사용]",
    "250": "천도교",
    "260": "[미사용]",
    "270": "힌두교, 브라만교",
    "280": "이슬람교(회교)",
    "290": "기타 제종교",
    "251": "교리",
    "252": "종교창시자(교주) 및 제자",
    "253": "경전, 성전",
    "254": "신앙록, 신앙생활, 수도생활",
    "255": "선교, 포교, 전도, 교육 활동",
    "256": "종단, 교단(교단론)",
    "257": "예배형식, 의식, 의례",
    "258": "동학교분파",
    "259": "단군교, 대종교",
    "261": "[미사용]",
    "262": "[미사용]",
    "263": "[미사용]",
    "264": "[미사용]",
    "265": "[미사용]",
    "266": "[미사용]",
    "267": "[미사용]",
    "268": "[미사용]",
    "269": "[미사용]",
    "271": "교리, 교의",
    "272": "창시자(교주) 및 제자",
    "273": "경전, 성전",
    "274": "신앙록, 신앙생활, 수도생활",
    "275": "선교, 포교, 전도, 교육 활동",
    "276": "종단, 교단",
    "277": "예배형식, 의식, 의례",
    "278": "종파, 교파",
    "279": "자이나교",
    "281": "교리, 교의",
    "282": "교창시자(교주) 및 제자",
    "283": "경전, 성전",
    "284": "신앙록, 신앙생활, 수도생활",
    "285": "선교, 포교, 전도, 교육 활동",
    "286": "종단, 교단",
    "287": "예배형식, 의식, 의례",
    "288": "종파, 교파",
    "289": "조로아스터교(요교, 배화교)",
    "291": "아시아",
    "292": "유럽",
    "293": "아프리카",
    "294": "북아메리카",
    "295": "남아메리카",
    "296": "오세아니아, 양극지방",
    "297": "[미사용]",
    "298": "[미사용]",
    "299": "기타 다른 기원의 종교",
    "300": "사회과학",
    "310": "통계자료",
    "320": "경제학",
    "330": "사회학, 사회문제",
    "340": "정치학",
    "301": "사회사상",
    "302": "잡저",
    "303": "사전(辭典), 사전(事典)",
    "304": "강연집, 수필집, 연설문집",
    "305": "연속간행물",
    "306": "학회, 단체, 협회, 기관, 회의",
    "307": "연구법, 연구방법 및 교육, 교육자료",
    "308": "총서, 전집, 선집",
    "309": "사회·문화 사정",
    "311": "아시아",
    "312": "유럽",
    "313": "아프리카",
    "314": "북아메리카",
    "315": "남아메리카",
    "316": "오세아니아, 양극지방",
    "317": "일반지역",
    "318": "[미사용]",
    "319": "인구통계",
    "321": "경제각론",
    "322": "경제정책",
    "323": "산업경제, 일반",
    "324": "기업경제",
    "325": "경영",
    "326": "상업, 교통, 통신",
    "327": "금융",
    "328": "보험",
    "329": "재정",
    "331": "사회학",
    "332": "사회 조직 및 제도",
    "333": "[미사용]",
    "334": "사회문제",
    "335": "생활문제",
    "336": "[미사용]",
    "337": "여성문제",
    "338": "사회복지",
    "339": "사회단체",
    "341": "국가형태",
    "342": "국가와 개인 및 집단",
    "343": "[미사용]",
    "344": "선거",
    "345": "입법",
    "346": "정당",
    "347": "[미사용]",
    "348": "[미사용]",
    "349": "외교, 국제관계",
    "350": "행정학",
    "360": "법률, 법학",
    "370": "교육학",
    "380": "풍습, 예절, 민속학",
    "390": "국방, 군사학",
    "351": "아시아",
    "352": "유럽",
    "353": "아프리카",
    "354": "북아메리카",
    "355": "남아메리카",
    "356": "오세아니아, 양극지방",
    "357": "일반지역",
    "358": "[미사용]",
    "359": "지방자치 및 지방행정",
    "361": "국제법",
    "362": "헌법",
    "363": "행정법",
    "364": "형법",
    "365": "민법",
    "366": "상법",
    "367": "사법제도 및 소송법",
    "368": "기타 제법",
    "369": "각국 법 및 예규",
    "371": "교육 정책 및 행정",
    "372": "학교 행정 및 경영, 보건 및 교육지도",
    "373": "학습지도, 교육방법",
    "374": "교육과정",
    "375": "유아 및 초등교육",
    "376": "중등교육",
    "377": "대학, 전문, 고등 교육",
    "378": "평생교육",
    "379": "특수교육",
    "381": "의식주의 풍습",
    "382": "연령별, 성별, 신분별, 사회계층의 풍습",
    "383": "사회생활의 풍습",
    "384": "관혼상제",
    "385": "예절",
    "386": "축제, 세시풍속",
    "387": "[미사용]",
    "388": "민속학",
    "389": "문화인류학",
    "391": "군사행정",
    "392": "전략, 전술",
    "393": "군사 교육 및 훈련",
    "394": "군사 시설 및 장비",
    "395": "군특수기술근무",
    "396": "육군",
    "397": "해군",
    "398": "공군",
    "399": "고대병법",
    "400": "자연과학",
    "410": "수학",
    "420": "물리학",
    "430": "화학",
    "440": "천문학",
    "401": "철학 및 이론",
    "402": "잡저(편람, 제표, 서지, 인명록)",
    "403": "사전, 백과사전",
    "404": "강연집, 수필집, 연설문집",
    "405": "연속간행물",
    "406": "학회, 단체, 기관, 회의",
    "407": "지도법, 연구법 및 교육, 교육자료",
    "408": "전집, 총서",
    "409": "과학사",
    "411": "산수",
    "412": "대수학",
    "413": "통계학",
    "414": "해석학",
    "415": "기하학",
    "416": "위상수학",
    "417": "삼각법",
    "418": "해석기하학",
    "419": "기타 산법",
    "421": "고체역학",
    "422": "유체역학",
    "423": "기체역학",
    "424": "음향학, 진동학",
    "425": "광학",
    "426": "열학",
    "427": "전기학 및 전자학",
    "428": "자기",
    "429": "현대물리학",
    "431": "이론화학과 물리화학",
    "432": "화학 실험실, 기기, 시설",
    "433": "분석화학",
    "434": "합성화학 일반",
    "435": "무기화학",
    "436": "금속원소와 그 화합물",
    "437": "유기화학",
    "438": "고리형화합물",
    "439": "고분자화합물과 기타 유기물",
    "441": "이론천문학",
    "442": "실지천문학",
    "443": "기술천문학",
    "444": "[미사용]",
    "445": "지구",
    "446": "측지학",
    "447": "항해천문학",
    "448": "역법, 측시법",
    "449": "각국의 역",
    "450": "지학",
    "460": "광물학",
    "470": "생명과학",
    "480": "식물학",
    "490": "동물학",
    "451": "지구물리학",
    "452": "지형학",
    "453": "기상학, 기후학",
    "454": "해양학",
    "455": "구조지질학",
    "456": "지사학",
    "457": "고생물학(화석학)",
    "458": "응용지질학 일반 및 광상학",
    "459": "암석학",
    "461": "원소광물",
    "462": "황화광물",
    "463": "할로겐화광물",
    "464": "산화광물",
    "465": "규산 및 규산염광물",
    "466": "기타 산화물을 포함한 광물",
    "467": "유기광물",
    "468": "[미사용]",
    "469": "결정학",
    "471": "인류학",
    "472": "생물학",
    "473": "생명론, 생물철학",
    "474": "세포학(세포생물학)",
    "475": "미생물학",
    "476": "생물진화",
    "477": "생물지리학",
    "478": "현미경 및 현미경검사법 일반",
    "479": "생물 채집 및 보존",
    "481": "일반 식물학",
    "482": "은화식물",
    "483": "엽상식물",
    "484": "조균류",
    "485": "현화식물, 종자식물",
    "486": "나자식물",
    "487": "피자식물",
    "488": "단자엽식물",
    "489": "쌍자엽식물",
    "491": "일반 동물학",
    "492": "무척추동물",
    "493": "원생동물, 해면동물, 자포동물, 선형동물",
    "494": "연체동물, 의연체동물",
    "495": "절지동물, 곤충류",
    "496": "척삭(척색)동물",
    "497": "어류, 양서류, 파충류",
    "498": "조류",
    "499": "포유류",
    "500": "기술과학",
    "510": "의학",
    "520": "농업, 농학",
    "530": "공학, 공업일반, 토목공학, 환경공학",
    "540": "건축, 건축학",
    "501": "기술 철학 및 이론",
    "502": "잡저",
    "503": "사전, 백과사전, 용어집",
    "504": "강연집, 수필집, 연설문집",
    "505": "연속간행물",
    "506": "학회, 단체, 기관, 회의",
    "507": "연구법 및 교육지도법",
    "508": "전집, 총서",
    "509": "기술사",
    "511": "기초의학",
    "512": "임상의학 일반",
    "513": "내과학",
    "514": "외과",
    "515": "치과의학, 이비인후과학, 안과학 및 기타 임상의학",
    "516": "산부인과, 소아과학",
    "517": "건강증진, 공중보건 및 예방의학",
    "518": "약학",
    "519": "한의학",
    "521": "농업기초학",
    "522": "농업경제",
    "523": "재배 및 보호",
    "524": "작물학",
    "525": "원예",
    "526": "임학, 임업",
    "527": "축산학",
    "528": "수의학",
    "529": "수산업, 생물자원의 보호, 수렵업",
    "531": "토목공학",
    "532": "토목역학, 토목재료",
    "533": "측량",
    "534": "도로공학",
    "535": "철도공학",
    "536": "교량공학",
    "537": "수리공학",
    "538": "항만공학",
    "539": "위생, 도시, 환경 공학",
    "541": "건축재료",
    "542": "건축 시공 및 적산",
    "543": "구조역학 및 건축일반구조",
    "544": "친환경건축 및 특정목적건축",
    "545": "건물 세부구조",
    "546": "건축환경, 설비, 배관 및 파이프 부설",
    "547": "난방, 환기 및 공기조화 공학",
    "548": "건축마감 및 인테리어",
    "549": "각종 건물",
    "550": "기계공학",
    "560": "전기공학, 통신공학, 전자공학",
    "570": "화학공학",
    "580": "제조업",
    "590": "생활과학",
    "551": "기계 역학, 요소 및 설계",
    "552": "공구와 가공장비",
    "553": "열공학과 원동기",
    "554": "유체역학, 공기역학, 전공학",
    "555": "정밀기계",
    "556": "자동차공학",
    "557": "철도차량, 기관차",
    "558": "항공우주공학, 우주항법학",
    "559": "기타공학",
    "561": "전기 회로, 계측, 재료",
    "562": "전기 기계 및 기구",
    "563": "발전",
    "564": "송전, 배전",
    "565": "전등, 조명, 전열",
    "566": "[미사용]",
    "567": "통신공학",
    "568": "무선공학",
    "569": "전자공학",
    "571": "공업화학약품",
    "572": "폭발물, 연료 공업",
    "573": "음료기술",
    "574": "식품공학",
    "575": "납, 유지, 석유, 가스 공업",
    "576": "요업 및 관련공업",
    "577": "세탁, 염색 및 관련공업",
    "578": "고분자화학공업",
    "579": "기타 유기화학공업",
    "581": "금속 제조 및 가공업",
    "582": "철 및 강철 제품",
    "583": "철기류 및 소규모철공",
    "584": "제재업, 목공업, 목제품",
    "585": "피혁 및 모피 공업",
    "586": "펄프, 종이 및 관련공업",
    "587": "직물 및 섬유 공업",
    "588": "의류제조",
    "589": "소형상품제조",
    "591": "가정관리 및 가정생활",
    "592": "의복",
    "593": "몸치장(몸단장), 화장",
    "594": "식품과 음료",
    "595": "주택관리 및 가정설비",
    "596": "공동주거용 주택 시설관리",
    "597": "가정위생",
    "598": "육아",
    "599": "[미사용]",
    "600": "예술",
    "610": "[미사용]",
    "620": "조각, 조형미술",
    "630": "공예",
    "640": "서예",
    "601": "미술이론, 미학",
    "602": "미술 재료 및 기법",
    "603": "미술 용어사전, 백과사전",
    "604": "미술의 주제",
    "605": "미술연속간행물",
    "606": "미술분야의 학회, 단체, 기관, 회의",
    "607": "미술의 지도법, 연구법 및 교육, 교육자료",
    "608": "미술 전집, 총서",
    "609": "미술사",
    "611": "[미사용]",
    "612": "[미사용]",
    "613": "[미사용]",
    "614": "[미사용]",
    "615": "[미사용]",
    "616": "[미사용]",
    "617": "[미사용]",
    "618": "[미사용]",
    "619": "[미사용]",
    "621": "[미사용]",
    "622": "조소 재료 및 기법",
    "623": "목조",
    "624": "석조",
    "625": "금동조",
    "626": "점토조소, 소조",
    "627": "기타 재료",
    "628": "전각, 인장",
    "629": "제상",
    "631": "도자공예, 유리공예",
    "632": "금속공예",
    "633": "보석, 갑각, 패류, 알 공예",
    "634": "목, 죽, 화훼, 왕골 공예",
    "635": "칠공예",
    "636": "염직물공예, 섬유공예",
    "637": "고무, 플라스틱 공예",
    "638": "미술가구",
    "639": "[미사용]",
    "641": "한자서체",
    "642": "한자서법",
    "643": "한글서체",
    "644": "기타 서법",
    "645": "[미사용]",
    "646": "펜습자",
    "647": "낙관, 수결(서명)",
    "648": "서보, 서첩, 법첩",
    "649": "문방구",
    "650": "회화, 도화, 디자인",
    "660": "사진예술",
    "670": "음악",
    "680": "공연예술, 매체예술",
    "690": "오락, 스포츠",
    "651": "채색 이론 및 실제",
    "652": "회화의 재료 및 기법",
    "653": "시대별 및 국별 회화",
    "654": "주제별 회화",
    "655": "[미사용]",
    "656": "소묘, 도화",
    "657": "만화, 삽화",
    "658": "디자인",
    "659": "판화",
    "661": "사진기, 사진재료",
    "662": "사진촬영기술",
    "663": "음화처리",
    "664": "양화처리(인화)",
    "665": "[미사용]",
    "666": "특수사진술",
    "667": "사진응용",
    "668": "사진집",
    "669": "[미사용]",
    "671": "음악 이론 및 기법",
    "672": "종교음악",
    "673": "성악",
    "674": "극음악, 오페라",
    "675": "기악합주",
    "676": "건반악기 및 타악기",
    "677": "현악기",
    "678": "관악기(취주악기)",
    "679": "한국음악 및 동양전통음악",
    "681": "극장, 제작, 연출, 연기",
    "682": "연희",
    "683": "[미사용]",
    "684": "각종 연극",
    "685": "무용, 발레",
    "686": "라디오극(방송극) 및 음성(소리)매체 예술",
    "687": "텔레비전극 및 시청각매체 방송 예술",
    "688": "영화",
    "689": "대중연예",
    "691": "오락",
    "692": "체육학, 스포츠",
    "693": "체조, 놀이",
    "694": "육상경기",
    "695": "구기",
    "696": "수상경기, 공중경기",
    "697": "동계스포츠",
    "698": "무예 및 기타 경기",
    "699": "기타 오락 및 레저스포츠",
    "700": "언어",
    "710": "한국어",
    "720": "중국어",
    "730": "일본어 및 기타 아시아 제어",
    "740": "영어",
    "701": "언어학",
    "702": "잡저",
    "703": "사전",
    "704": "강연집, 수필집",
    "705": "연속간행물",
    "706": "학회, 단체, 기관, 회의",
    "707": "지도법, 연구법 및 교육, 교육자료",
    "708": "전집, 총서",
    "709": "언어사 및 언어정책, 언어행정",
    "711": "음운, 음성, 문자",
    "712": "어원, 어의",
    "713": "사전",
    "714": "어휘",
    "715": "문법",
    "716": "작문",
    "717": "독본, 해석, 회화",
    "718": "방언(사투리)",
    "719": "[미사용]",
    "721": "음운, 음성, 문자",
    "722": "어원, 어의",
    "723": "사전",
    "724": "어휘",
    "725": "문법, 어법",
    "726": "작문",
    "727": "독본, 해석, 회화",
    "728": "방언(사투리)",
    "729": "[미사용]",
    "731": "음운, 음성, 문자",
    "732": "어원, 어의",
    "733": "사전",
    "734": "어휘",
    "735": "문법, 어법",
    "736": "작문",
    "737": "독본, 해석, 회화",
    "738": "방언(사투리)",
    "739": "기타 아시아 제어",
    "741": "음운, 음성, 문자",
    "742": "어원, 어의",
    "743": "사전",
    "744": "어휘",
    "745": "문법",
    "746": "작문",
    "747": "독본, 해석, 회화",
    "748": "방언(사투리)",
    "749": "앵글로색슨어",
    "750": "독일어",
    "760": "프랑스어",
    "770": "스페인어 및 포르투갈어",
    "780": "이탈리아어",
    "790": "기타 제어",
    "751": "음운, 음성, 문자",
    "752": "어원, 어의",
    "753": "사전",
    "754": "어휘",
    "755": "문법",
    "756": "작문",
    "757": "독본, 해석, 회화",
    "758": "방언(사투리)",
    "759": "기타 게르만어파",
    "761": "음운, 음성, 문자",
    "762": "어원, 어의",
    "763": "사전",
    "764": "어휘",
    "765": "문법",
    "766": "작문",
    "767": "독본, 해석, 회화",
    "768": "방언(사투리)",
    "769": "프로방스어",
    "771": "음운, 음성, 문자",
    "772": "어원, 어의",
    "773": "사전",
    "774": "어휘",
    "775": "문법",
    "776": "작문",
    "777": "독본, 해석, 회화",
    "778": "방언(사투리)",
    "779": "포르투갈어",
    "781": "음운, 음성, 문자",
    "782": "어원, 어의",
    "783": "사전",
    "784": "어휘",
    "785": "문법",
    "786": "작문",
    "787": "독본, 해석, 회화",
    "788": "방언(사투리)",
    "789": "루마니아어",
    "791": "[미사용]",
    "792": "인도-유럽어족",
    "793": "아프리카 제어",
    "794": "북아메리카 인디언어",
    "795": "남아메리카 인디언어",
    "796": "오스트로네시아어족",
    "797": "셈어족(셈어파)",
    "798": "함어족(함어파)",
    "799": "국제어(인공어) 및 기타 언어",
    "800": "문학",
    "810": "한국문학",
    "820": "중국문학",
    "830": "일본문학 및 기타 아시아 제문학",
    "840": "영미문학",
    "801": "문학이론",
    "802": "문장작법, 수사학",
    "803": "사전(辭典), 사전(事典)",
    "804": "수필집, 강연집",
    "805": "연속간행물",
    "806": "학회, 단체, 기관, 회의",
    "807": "지도법 및 연구법, 교육, 교육자료",
    "808": "전집, 총서",
    "809": "문학사, 평론",
    "811": "시",
    "812": "희곡",
    "813": "소설",
    "814": "수필",
    "815": "연설, 웅변",
    "816": "일기, 서간, 기행",
    "817": "풍자 및 유머",
    "818": "르포르타주 및 기타",
    "819": "[미사용]",
    "821": "시",
    "822": "희곡",
    "823": "소설",
    "824": "수필",
    "825": "연설, 웅변",
    "826": "일기, 서간, 기행",
    "827": "풍자 및 유머",
    "828": "르포르타주 및 기타",
    "829": "[미사용]",
    "831": "시",
    "832": "희곡",
    "833": "소설",
    "834": "수필",
    "835": "연설, 웅변",
    "836": "일기, 서간, 기행",
    "837": "풍자 및 유머",
    "838": "르포르타주 및 기타",
    "839": "기타 아시아 제문학",
    "841": "시",
    "842": "희곡",
    "843": "소설",
    "844": "수필",
    "845": "연설, 웅변",
    "846": "일기, 서간, 기행",
    "847": "풍자 및 유머",
    "848": "르포르타주 및 기타",
    "(849)": "미국문학",
    "850": "독일문학",
    "860": "프랑스 문학",
    "870": "스페인 및 포르투갈 문학",
    "880": "이탈리아 문학",
    "890": "기타 제문학",
    "851": "시",
    "852": "희곡",
    "853": "소설",
    "854": "수필",
    "855": "연설, 웅변",
    "856": "일기, 서간, 기행",
    "857": "풍자 및 유머",
    "858": "르포르타주 및 기타",
    "859": "기타 게르만문학",
    "861": "시",
    "862": "희곡",
    "863": "소설",
    "864": "수필",
    "865": "연설, 웅변",
    "866": "일기, 서간, 기행",
    "867": "풍자 및 유머",
    "868": "르포르타주 및 기타",
    "869": "프로방스문학",
    "871": "시",
    "872": "희곡",
    "873": "소설",
    "874": "수필",
    "875": "연설, 웅변",
    "876": "일기, 서간, 기행",
    "877": "풍자 및 유머",
    "878": "르포르타주 및 기타",
    "879": "포르투갈문학",
    "881": "시",
    "882": "희곡",
    "883": "소설",
    "884": "수필",
    "885": "연설, 웅변",
    "886": "일기, 서간, 기행",
    "887": "풍자 및 유머",
    "888": "르포르타주 및 기타",
    "889": "루마니아문학",
    "891": "[미사용]",
    "892": "인도-유럽계문학",
    "893": "아프리카 제문학",
    "894": "북아메리카 인디언문학",
    "895": "남아메리카 인디언문학",
    "896": "오스트로네시아문학",
    "897": "셈족문학",
    "898": "함족문학",
    "899": "기타 문학",
    "900": "역사",
    "910": "아시아",
    "920": "유럽",
    "930": "아프리카",
    "940": "북아메리카",
    "901": "역사 철학 및 이론",
    "902": "역사보조학",
    "903": "사전(辭典), 사전(事典)",
    "904": "강연집, 사평",
    "905": "연속간행물",
    "906": "학회, 단체, 기관, 회의",
    "907": "지도법, 연구법 및 교육, 교육자료",
    "908": "전집, 총서",
    "909": "세계사, 세계문화사",
    "911": "한국",
    "912": "중국",
    "913": "일본",
    "914": "동남아시아",
    "915": "인디아와 남부아시아",
    "916": "중앙아시아",
    "917": "시베리아",
    "918": "서남아시아, 중동",
    "919": "아라비아반도와 인접지역",
    "921": "고대 그리스(희랍고대사)",
    "922": "고대 로마",
    "923": "스칸디나비아",
    "924": "영국, 아일랜드",
    "925": "독일과 중앙유럽",
    "926": "프랑스와 인접국가",
    "927": "스페인과 인접국가",
    "928": "이탈리아와 인접국가",
    "929": "러시아와 동부유럽",
    "931": "북아프리카",
    "932": "[미사용]",
    "933": "[미사용]",
    "934": "서아프리카",
    "935": "[미사용]",
    "936": "중앙아프리카",
    "937": "동아프리카",
    "938": "남아프리카",
    "939": "남인도양제도",
    "941": "캐나다",
    "942": "미국(미합중국)",
    "943": "멕시코",
    "944": "중앙아메리카(중미제국)",
    "945": "과테말라, 벨리즈, 엘살바도르",
    "946": "온두라스",
    "947": "니카라과",
    "948": "코스타리카, 파나마",
    "949": "서인도제도",
    "950": "남아메리카",
    "960": "오세아니아, 양극지방",
    "970": "[미사용]",
    "980": "지리",
    "990": "전기",
    "951": "콜롬비아",
    "952": "베네수엘라와 기아나 지역",
    "953": "브라질",
    "954": "에콰도르",
    "955": "페루",
    "956": "볼리비아",
    "957": "파라과이, 우루과이",
    "958": "아르헨티나",
    "959": "칠레",
    "961": "[미사용]",
    "962": "오스트레일리아(호주)",
    "963": "뉴질랜드",
    "964": "파푸아뉴기니",
    "965": "멜라네시아",
    "966": "미크로네시아와 인접국가",
    "967": "폴리네시아와 하와이",
    "968": "대서양제도",
    "969": "양극지방",
    "971": "[미사용]",
    "972": "[미사용]",
    "973": "[미사용]",
    "974": "[미사용]",
    "975": "[미사용]",
    "976": "[미사용]",
    "977": "[미사용]",
    "978": "[미사용]",
    "979": "[미사용]",
    "981": "아시아지리",
    "982": "유럽지리",
    "983": "아프리카지리",
    "984": "북아메리카지리",
    "985": "남아메리카지리",
    "986": "오세아니아지리와 양극 지리",
    "987": "지역구분 일반지리",
    "988": "해양",
    "989": "지도 및 지도책",
    "991": "아시아전기",
    "992": "유럽전기",
    "993": "아프리카전기",
    "994": "북아메리카전기",
    "995": "남아메리카전기",
    "996": "오세아니아와 양극 전기",
    "997": "[미사용]",
    "998": "주제별 전기",
    "999": "계보, 족보",
}

ddc_dict = {
    "000": "Generalities",
    "001": "Knowledge",
    "002": "The book",
    "003": "Systems",
    "004": "Data processing Computer science",
    "005": "Computer programming, programs, data",
    "006": "Special computer methods",
    "007": "Not assigned or no longer used",
    "008": "Not assigned or no longer used",
    "009": "Not assigned or no longer used",
    "010": "Bibliography",
    "011": "Bibliographies",
    "012": "Bibliographies of individuals",
    "013": "Bibliographies of works by specific classes of authors",
    "014": "Bibliographies of anonymous and pseudonymous works",
    "015": "Bibliographies of works from specific places",
    "016": "Bibliographies of works from specific subjects",
    "017": "General subject catalogs",
    "018": "Catalogs arranged by author & date",
    "019": "Dictionary catalogs",
    "020": "Library & information sciences",
    "021": "Library relationships",
    "022": "Administration of the physical plant",
    "023": "Personnel administration",
    "024": "Not assigned or no longer used",
    "025": "Library operations",
    "026": "Libraries for specific subjects",
    "027": "General libraries",
    "028": "Reading, use of other information media",
    "029": "Not assigned or no longer used",
    "030": "General encyclopedic works",
    "031": "General encyclopedic works — American",
    "032": "General encyclopedic works in English",
    "033": "General encyclopedic works in other Germanic languages",
    "034": "General encyclopedic works in French, Provencal, Catalan",
    "035": "General encyclopedic works in Italian, Romanian, Rhaeto-Romanic",
    "036": "General encyclopedic works in Spanish & Portuguese",
    "037": "General encyclopedic works in Slavic languages",
    "038": "General encyclopedic works in Scandinavian languages",
    "039": "General encyclopedic works in other languages",
    "040": "Not assigned or no longer used",
    "041": "Not assigned or no longer used",
    "042": "Not assigned or no longer used",
    "043": "Not assigned or no longer used",
    "044": "Not assigned or no longer used",
    "045": "Not assigned or no longer used",
    "046": "Not assigned or no longer used",
    "047": "Not assigned or no longer used",
    "048": "Not assigned or no longer used",
    "049": "Not assigned or no longer used",
    "050": "General serials & their indexes",
    "051": "General serials & their indexes American",
    "052": "General serials & their indexes In English",
    "053": "General serials & their indexes In other Germanic languages",
    "054": "General serials & their indexes In French, Provencal, Catalan",
    "055": "General serials & their indexes In Italian, Romanian, Rhaeto-Romanic",
    "056": "General serials & their indexes In Spanish & Portuguese",
    "057": "General serials & their indexes In Slavic languages",
    "058": "General serials & their indexes In Scandinavian languages",
    "059": "General serials & their indexes In other languages",
    "060": "General organization & museology",
    "061": "General organization & museology In North America",
    "062": "General organization & museology In British Isles In England",
    "063": "General organization & museology In central Europe In Germany",
    "064": "General organization & museology In France & Monaco",
    "065": "General organization & museology In Italy & adjacent territories",
    "066": "General organization & museology In Iberian Peninsula & adjacent islands",
    "067": "General organization & museology In eastern Europe In Soviet Union",
    "068": "General organization & museology In other areas",
    "069": "Museology (Museum science)",
    "070": "News media, journalism, publishing",
    "071": "News media, journalism, publishing In North America",
    "072": "News media, journalism, publishing In British Isles In England",
    "073": "News media, journalism, publishing In central Europe In Germany",
    "074": "News media, journalism, publishing In France & Monaco",
    "075": "News media, journalism, publishing In Italy & adjacent territories",
    "076": "News media, journalism, publishing In Iberian Peninsula & adjacent islands",
    "077": "News media, journalism, publishing In eastern Europe In Soviet Union",
    "078": "News media, journalism, publishing In Scandinavia",
    "079": "News media, journalism, publishing In other languages",
    "080": "General collections",
    "081": "General collections American",
    "082": "General collections In English",
    "083": "General collections In other Germanic languages",
    "084": "General collections In French, Provencal, Catalan",
    "085": "General collections In Italian, Romanian, Rhaeto-Romanic",
    "086": "General collections In Spanish & Portuguese",
    "087": "General collections In Slavic languages",
    "088": "General collections In Scandinavian languages",
    "089": "General collections In other languages",
    "090": "Manuscripts & rare books",
    "091": "Manuscripts",
    "092": "Block books",
    "093": "Incunabula",
    "094": "Printed books",
    "095": "Books notable for bindings",
    "096": "Books notable for illustrations",
    "097": "Books notable for ownership or origin",
    "098": "Prohibited works, forgeries, hoaxes",
    "099": "Books notable for format",
    "100": "Philosophy & psychology",
    "101": "Theory of philosophy",
    "102": "Miscellany of philosophy",
    "103": "Dictionaries of philosophy",
    "104": "Not assigned or no longer used",
    "105": "Serial publications of philosophy",
    "106": "Organizations of philosophy",
    "107": "Education, research in philosophy",
    "108": "Kinds of persons in philosophy",
    "109": "Historical treatment of philosophy",
    "110": "Metaphysics",
    "111": "Ontology",
    "112": "Not assigned or no longer used",
    "113": "Cosmology (Philosophy of nature)",
    "114": "Space",
    "115": "Time",
    "116": "Change",
    "117": "Structure",
    "118": "Force & Energy",
    "119": "Number & quantity",
    "120": "Epistemology, causation, humankind",
    "121": "Epistemology (Theory of knowledge)",
    "122": "Causation",
    "123": "Determinism & indeterminism",
    "124": "Teleology",
    "125": "Not assigned or no longer used",
    "126": "The self",
    "127": "The unconscious & the subconscious",
    "128": "Humankind",
    "129": "Origin & destiny of individual souls",
    "130": "Paranormal phenomena",
    "131": "Occult methods for achieving well-being",
    "132": "Not assigned or no longer used",
    "133": "Parapsychology & occultism",
    "134": "Not assigned or no longer used",
    "135": "Dreams & mysteries",
    "136": "Not assigned or no longer used",
    "137": "Divinatory graphology",
    "138": "Physiognomy",
    "139": "Phrenology",
    "140": "Specific philosophical schools",
    "141": "Idealism & related systems",
    "142": "Critical philosophy",
    "143": "Intuitionism & Bergsonism",
    "144": "Humanism & related systems",
    "145": "Sensationalism",
    "146": "Naturalism & related systems",
    "147": "Pantheism & related systems",
    "148": "Liberalism, eclecticism, traditionalism",
    "149": "Other philosophical systems",
    "150": "Psychology",
    "151": "Not assigned or no longer used",
    "152": "Perception, movement, emotions, drives",
    "153": "Mental processes & intelligence",
    "154": "Subconscious & altered states",
    "155": "Differential & developmental psychology",
    "156": "Comparative psychology",
    "157": "Not assigned or no longer used",
    "158": "Applied psychology",
    "159": "Not assigned or no longer used",
    "160": "Logic",
    "161": "Induction",
    "162": "Deduction",
    "163": "Not assigned or no longer used",
    "164": "Not assigned or no longer used",
    "165": "Fallacies & sources of error",
    "166": "Syllogisms",
    "167": "Hypotheses",
    "168": "Argument & persuasion",
    "169": "Analogy",
    "170": "Ethics (Moral philosophy)",
    "171": "Systems & doctrines",
    "172": "Political ethics",
    "173": "Ethics of family relationships",
    "174": "Economic & professional ethics",
    "175": "Ethics of recreation & leisure",
    "176": "Ethics of sex & reproduction",
    "177": "Ethics of social relations",
    "178": "Ethics of consumption",
    "179": "Other ethical norms",
    "180": "Ancient, medieval, Oriental philosophy",
    "181": "Oriental philosophy",
    "182": "Pre-Socratic Greek philosophies",
    "183": "Sophistic & Socratic philosophies",
    "184": "Platonic philosophy",
    "185": "Aristotelian philosophy",
    "186": "Skeptic and Neoplatonic philosophies",
    "187": "Epicurean philosophy",
    "188": "Stoic philosophy",
    "189": "Medieval Western philosophy",
    "190": "Modern Western philosophy",
    "191": "Modern Western philosophy United States & Canada",
    "192": "Modern Western philosophy British Isles",
    "193": "Modern Western philosophy Germany & Austria",
    "194": "Modern Western philosophy France",
    "195": "Modern Western philosophy Italy",
    "196": "Modern Western philosophy Spain & Portugal",
    "197": "Modern Western philosophy Soviet Union",
    "198": "Modern Western philosophy Scandinavia",
    "199": "Modern Western philosophy Other geographical areas",
    "200": "Religion",
    "201": "Philosophy of Christianity",
    "202": "Miscellany of Christianity",
    "203": "Dictionaries of Christianity",
    "204": "Special topics",
    "205": "Serial publications of Christianity",
    "206": "Organizations of Christianity",
    "207": "Education, research in Christianity",
    "208": "Kinds of persons in Christianity",
    "209": "History & geography of Christianity",
    "210": "Natural theology",
    "211": "Concepts of God",
    "212": "Existence, attributes of God",
    "213": "Creation",
    "214": "Theodicy",
    "215": "Science & religion",
    "216": "Good & evil",
    "217": "Not assigned or no longer used",
    "218": "Humankind",
    "219": "Not assigned or no longer used",
    "220": "Bible",
    "221": "Old Testament",
    "222": "Historical books of Old Testament",
    "223": "Poetic books of Old Testament",
    "224": "Prophetic books of Old Testament",
    "225": "New Testament",
    "226": "Gospels & Acts",
    "227": "Epistles",
    "228": "Revelation (Apocalypse)",
    "229": "Apocrypha & pseudepigrapha",
    "230": "Christian theology",
    "231": "God",
    "232": "Jesus Christ & his family",
    "233": "Humankind",
    "234": "Salvation (Soteriology) & grace",
    "235": "Spiritual beings",
    "236": "Eschatology",
    "237": "Not assigned or no longer used",
    "238": "Creeds & catechisms",
    "239": "Apologetics & polemics",
    "240": "Christian moral & devotional theology",
    "241": "Moral theology",
    "242": "Devotional literature",
    "243": "Evangelistic writings for individuals",
    "244": "Not assigned or no longer used",
    "245": "Texts of hymns",
    "246": "Use of art in Christianity",
    "247": "Church furnishings & articles",
    "248": "Christian experience, practice, life",
    "249": "Christian observances in family life",
    "250": "Christian orders & local church",
    "251": "Preaching (Homiletics)",
    "252": "Texts of sermons",
    "253": "Pastoral office (Pastoral theology)",
    "254": "Parish government & administration",
    "255": "Religious congregations & orders",
    "256": "Not assigned or no longer used",
    "257": "Not assigned or no longer used",
    "258": "Not assigned or no longer used",
    "259": "Activities of the local church",
    "260": "Christian social theology",
    "261": "Social theology",
    "262": "Ecclesiology",
    "263": "Times, places of religious observance",
    "264": "Public worship",
    "265": "Sacraments, other rites & acts",
    "266": "Missions",
    "267": "Associations for religious work",
    "268": "Religious education",
    "269": "Spiritual renewal",
    "270": "Christian church history",
    "271": "Religious orders in church history",
    "272": "Persecutions in church history",
    "273": "Heresies in church history",
    "274": "Christian church in Europe",
    "275": "Christian church in Asia",
    "276": "Christian church in Africa",
    "277": "Christian church in North America",
    "278": "Christian church in South America",
    "279": "Christian church in other areas",
    "280": "Christian denominations & sects",
    "281": "Early church & Eastern churches",
    "282": "Roman Catholic Church",
    "283": "Anglican churches",
    "284": "Protestants of Continental origin",
    "285": "Presbyterian, Reformed, Congregational",
    "286": "Baptist, Disciples of Christ, Adventist",
    "287": "Methodist & related churches",
    "288": "Not assigned or no longer used",
    "289": "Other denominations & sects",
    "290": "Other & comparative religions",
    "291": "Comparative religion",
    "292": "Classical (Greek & Roman) religion",
    "293": "Germanic religion",
    "294": "Religions of Indic origin",
    "295": "Zoroastrianism (Mazdaism, Parseeism)",
    "296": "Judaism",
    "297": "Islam & religions originating in it",
    "298": "Not assigned or no longer used",
    "299": "Other religions",
    "300": "Social sciences",
    "301": "Sociology & anthropology",
    "302": "Social interaction",
    "303": "Social processes",
    "304": "Factors affecting social behavior",
    "305": "Social groups",
    "306": "Culture & institutions",
    "307": "Communities",
    "308": "Not assigned or no longer used",
    "309": "Not assigned or no longer used",
    "310": "General statistics",
    "311": "Not assigned or no longer used",
    "312": "Not assigned or no longer used",
    "313": "Not assigned or no longer used",
    "314": "General statistics Of Europe",
    "315": "General statistics Of Asia",
    "316": "General statistics Of Africa",
    "317": "General statistics Of North America",
    "318": "General statistics Of South America",
    "319": "General statistics Of other parts of the world",
    "320": "Political science",
    "321": "Systems of governments & states",
    "322": "Relation of state to organized groups",
    "323": "Civil & political rights",
    "324": "The political process",
    "325": "International migration & colonization",
    "326": "Slavery & emancipation",
    "327": "International relations",
    "328": "The legislative process",
    "329": "Not assigned or no longer used",
    "330": "Economics",
    "331": "Labor economics",
    "332": "Financial economics",
    "333": "Land economics",
    "334": "Cooperatives",
    "335": "Socialism & related systems",
    "336": "Public finance",
    "337": "International economics",
    "338": "Production",
    "339": "Macroeconomics & related topics",
    "340": "Law",
    "341": "International law",
    "342": "Constitutional & administrative law",
    "343": "Military, tax, trade, industrial law",
    "344": "Social, labor, welfare, & related law",
    "345": "Criminal law",
    "346": "Private law",
    "347": "Civil procedure & courts",
    "348": "Law (Statutes), regulations, cases",
    "349": "Law of specific jurisdictions & areas",
    "350": "Public administration",
    "351": "Of central governments",
    "352": "Of local governments",
    "353": "of U.S. federal & state governments",
    "354": "Of specific central governments",
    "355": "Military science",
    "356": "Foot forces & warfare",
    "357": "Mounted forces & warfare",
    "358": "Other specialized forces & services",
    "359": "Sea (Naval) forces & warfare",
    "360": "Social services; association",
    "361": "General social problems & services",
    "362": "Social welfare problems & services",
    "363": "Other social problems & services",
    "364": "Criminology",
    "365": "Penal & related institutions",
    "366": "Association",
    "367": "General clubs",
    "368": "Insurance",
    "369": "Miscellaneous kinds of associations",
    "370": "Education",
    "371": "School management; special education",
    "372": "Elementary education",
    "373": "Secondary education",
    "374": "Adult education",
    "375": "Curriculums",
    "376": "Education of women",
    "377": "Schools & religion",
    "378": "Higher education",
    "379": "Government regulation, control, support",
    "380": "Commerce, communications, transport",
    "381": "Internal commerce (Domestic trade)",
    "382": "International commerce (Foreign trade)",
    "383": "Postal communication",
    "384": "Communications Telecommunication",
    "385": "Railroad transportation",
    "386": "Inland waterway & ferry transportation",
    "387": "Water, air, space transportation",
    "388": "Transportation Ground transportation",
    "389": "Metrology & standardization",
    "390": "Customs, etiquette, folklore",
    "391": "Costume & personal appearance",
    "392": "Customs of life cycle & domestic life",
    "393": "Death customs",
    "394": "General customs",
    "395": "Etiquette (Manners)",
    "396": "Not assigned or no longer used",
    "397": "Not assigned or no longer used",
    "398": "Folklore",
    "399": "Customs of war & diplomacy",
    "400": "Language",
    "401": "Philosophy & theory",
    "402": "Miscellany",
    "403": "Dictionaries & encyclopedias",
    "404": "Special topics",
    "405": "Serial publications",
    "406": "Organizations & management",
    "407": "Education, research, related topics",
    "408": "With respect to kinds of persons",
    "409": "Geographical & persons treatment",
    "410": "Linguistics",
    "411": "Writing systems",
    "412": "Etymology",
    "413": "Dictionaries",
    "414": "Phonology",
    "415": "Structural systems (Grammar)",
    "416": "Not assigned or no longer used",
    "417": "Dialectology & historical linguistics",
    "418": "Standard usage Applied linguistics",
    "419": "Verbal language not spoken or written",
    "420": "English & Old English",
    "421": "English writing system & phonology",
    "422": "English etymology",
    "423": "English dictionaries",
    "424": "Not assigned or no longer used",
    "425": "English grammar",
    "426": "Not assigned or no longer used",
    "427": "English language variations",
    "428": "Standard English usage",
    "429": "Old English (Anglo-Saxon)",
    "430": "Germanic languages German",
    "431": "German writing system & phonology",
    "432": "German etymology",
    "433": "German dictionaries",
    "434": "Not assigned or no longer used",
    "435": "German grammar",
    "436": "Not assigned or no longer used",
    "437": "German language variations",
    "438": "Standard German usage",
    "439": "Other Germanic languages",
    "440": "Romance languages French",
    "441": "French writing system & phonology",
    "442": "French etymology",
    "443": "French dictionaries",
    "444": "Not assigned or no longer used",
    "445": "French grammar",
    "446": "Not assigned or no longer used",
    "447": "French language variations",
    "448": "Standard French usage",
    "449": "Provencal & Catalan",
    "450": "Italian, Romanian, Rhaeto-Romantic",
    "451": "Italian writing system & phonology",
    "452": "Italian etymology",
    "453": "Italian dictionaries",
    "454": "Not assigned or no longer used",
    "455": "Italian grammar",
    "456": "Not assigned or no longer used",
    "457": "Italian language variations",
    "458": "Standard Italian usage",
    "459": "Romanian & Rhaeto-Romanic",
    "460": "Spanish & Portuguese languages",
    "461": "Spanish writing system & phonology",
    "462": "Spanish etymology",
    "463": "Spanish dictionaries",
    "464": "Not assigned or no longer used",
    "465": "Spanish grammar",
    "466": "Not assigned or no longer used",
    "467": "Spanish language variations",
    "468": "Standard Spanish usage",
    "469": "Portuguese",
    "470": "Italic Latin",
    "471": "Classical Latin writing & phonology",
    "472": "Classical Latin etymology & phonology",
    "473": "Classical Latin dictionaries",
    "474": "Not assigned or no longer used",
    "475": "Classical Latin grammar",
    "476": "Not assigned or no longer used",
    "477": "Old, Postclassical, Vulgar Latin",
    "478": "Classical Latin usage",
    "479": "Other Italic languages",
    "480": "Hellenic languages Classical Greek",
    "481": "Classical Greek writing & phonology",
    "482": "Classical Greek etymology",
    "483": "Classical Greek dictionaries",
    "484": "Not assigned or no longer used",
    "485": "Classical Greek grammar",
    "486": "Not assigned or no longer used",
    "487": "Preclassical & postclassical Greek",
    "488": "Classical Greek usage",
    "489": "Other Hellenic languages",
    "490": "Other languages",
    "491": "East Indo-European & Celtic languages",
    "492": "Afro-Asiatic languages Semitic",
    "493": "Non-Semitic Afro-Asiatic languages",
    "494": "Ural-Altaic, Paleosiberian, Dravidian",
    "495": "Languages of East & Southeast Asia",
    "496": "African languages",
    "497": "North American native languages",
    "498": "South American native languages",
    "499": "Miscellaneous languages",
    "500": "Natural sciences & mathematics",
    "501": "Philosophy & theory",
    "502": "Miscellany",
    "503": "Dictionaries & encyclopedias",
    "504": "Not assigned or no longer used",
    "505": "Serial publications",
    "506": "Organizations & management",
    "507": "Education, research, related topics",
    "508": "Natural history",
    "509": "Historical, areas, persons treatment",
    "510": "Mathematics",
    "511": "General principles",
    "512": "Algebra & number theory",
    "513": "Arithmetic",
    "514": "Topology",
    "515": "Analysis",
    "516": "Geometry",
    "517": "Not assigned or no longer used",
    "518": "Not assigned or no longer used",
    "519": "Probabilities & applied mathematics",
    "520": "Astronomy & allied sciences",
    "521": "Celestial mechanics",
    "522": "Techniques, equipment, materials",
    "523": "Specific celestial bodies & phenomena",
    "524": "Not assigned or no longer used",
    "525": "Earth (Astronomical geography)",
    "526": "Mathematical geography",
    "527": "Celestial navigation",
    "528": "Ephemerides",
    "529": "Chronology",
    "530": "Physics",
    "531": "Classical mechanics Solid mechanics",
    "532": "Fluid mechanics Liquid mechanics",
    "533": "Gas mechanics",
    "534": "Sound & related vibrations",
    "535": "Light & paraphotic phenomena",
    "536": "Heat",
    "537": "Electricity & electronics",
    "538": "Magnetism",
    "539": "Modern physics",
    "540": "Chemistry & allied sciences",
    "541": "Physical & theoretical chemistry",
    "542": "Techniques, equipment, materials",
    "543": "Analytical chemistry",
    "544": "Qualitative analysis",
    "545": "Quantitative analysis",
    "546": "Inorganic chemistry",
    "547": "Organic chemistry",
    "548": "Crystallography",
    "549": "Mineralogy",
    "550": "Earth sciences",
    "551": "Geology, hydrology, meteorology",
    "552": "Petrology",
    "553": "Economic geology",
    "554": "Earth sciences of Europe",
    "555": "Earth sciences of Asia",
    "556": "Earth sciences of Africa",
    "557": "Earth sciences of North America",
    "558": "Earth sciences of South America",
    "559": "Earth sciences of other areas",
    "560": "Paleontology Paleozoology",
    "561": "Paleobotany",
    "562": "Fossil invertebrates",
    "563": "Fossil primitive phyla",
    "564": "Fossil Mollusca & Molluscoidea",
    "565": "Other fossil invertebrates",
    "566": "Fossil Vertebrata (Fossil Craniata)",
    "567": "Fossilcold-blooded vertebrates",
    "568": "Fossil Aves (Fossil birds)",
    "569": "Fossil Mammalia",
    "570": "Life sciences",
    "571": "Not assigned or no longer used",
    "572": "Biochemistry",
    "573": "Physical anthropology",
    "574": "Biology",
    "575": "Evolution & genetics",
    "576": "Microbiology",
    "577": "General nature of life",
    "578": "Microscopy in biology",
    "579": "Collection and preservation",
    "580": "Botanical sciences",
    "581": "Botany",
    "582": "Spermatophyta (Seed-bearing plants)",
    "583": "Dicotyledones",
    "584": "Monocotyledones",
    "585": "Gymnospermae (Pinophyta)",
    "586": "Cryptogamia (Seedless plants)",
    "587": "Pteridophyta (Vascular cryptograms)",
    "588": "Bryophyta",
    "589": "Thallobionta & Prokaryotae",
    "590": "Zoological sciences",
    "591": "Zoology",
    "592": "Invertebrates",
    "593": "Protozoa, Echinodermata, related phyla",
    "594": "Mollusca & Molluscoidea",
    "595": "Other invertebrates",
    "596": "Vertebrata (Craniata, Vertebrates)",
    "597": "Cold-blooded vertebrates Fishes",
    "598": "Aves (Birds)",
    "599": "Mammalia (Mammals)",
    "600": "Technology (Applied sciences)",
    "601": "Philosophy & theory",
    "602": "Miscellany",
    "603": "Dictionaries & encyclopedias",
    "604": "Special topics",
    "605": "Serial publications",
    "606": "Organizations",
    "607": "Education, research, related topics",
    "608": "Invention & patents",
    "609": "Historical, areas, persons treatment",
    "610": "Medical sciences Medicine",
    "611": "Human anatomy, cytology, histology",
    "612": "Human physiology",
    "613": "Promotion of health",
    "614": "Incidence & prevention of disease",
    "615": "Pharmacology & theraputics",
    "616": "Diseases",
    "617": "Surgery & related medical specialities",
    "618": "Gynecology & other medical specialities",
    "619": "Experimental medicine",
    "620": "Engineering & allied operations",
    "621": "Applied physics",
    "622": "Mining & related operations",
    "623": "Military & nautical engineering",
    "624": "Civil engineering",
    "625": "Engineering of railroads, roads",
    "626": "Not assigned or no longer used",
    "627": "Hydraulic engineering",
    "628": "Sanitary & municipal engineering",
    "629": "Other branches of engineering",
    "630": "Agriculture",
    "631": "Techniques, equipment, materials",
    "632": "Plant injuries, diseases, pests",
    "633": "Field & plantation crops",
    "634": "Orchards, fruits, forestry",
    "635": "Garden crops (Horticulture)",
    "636": "Animal husbandry",
    "637": "Processing dairy & related products",
    "638": "Insect culture",
    "639": "Hunting, fishing, conservation",
    "640": "Home economics & family living",
    "641": "Food & drink",
    "642": "Meals & table service",
    "643": "Housing & household equipment",
    "644": "Household utilities",
    "645": "Household furnishings",
    "646": "Sewing, clothing, personal living",
    "647": "Management of public households",
    "648": "Housekeeping",
    "649": "Child rearing & home care of sick",
    "650": "Management & auxiliary services",
    "651": "Office services",
    "652": "Processes of written communication",
    "653": "Shorthand",
    "654": "Not assigned or no longer used",
    "655": "Not assigned or no longer used",
    "656": "Not assigned or no longer used",
    "657": "Accounting",
    "658": "General management",
    "659": "Advertising & public relations",
    "660": "Chemical engineering",
    "661": "Industrial chemicals technology",
    "662": "Explosives, fuels technology",
    "663": "Beverage technology",
    "664": "Food technology",
    "665": "Industrial oils, fats, waxes, gases",
    "666": "Ceramic & allied technologies",
    "667": "Cleaning, color, related technologies",
    "668": "Technology of other organic products",
    "669": "Metallurgy",
    "670": "Manufacturing",
    "671": "Metalworking & metal products",
    "672": "Iron, steel, other iron alloys",
    "673": "Nonferrous metals",
    "674": "Lumber processing, wood products, cork",
    "675": "Leather & fur processing",
    "676": "Pulp & paper technology",
    "677": "Textiles",
    "678": "Elastomers & elastomer products",
    "679": "Other products of specific materials",
    "680": "Manufacture for specific uses",
    "681": "Precision instruments & other devices",
    "682": "Small forge work (Blacksmithing)",
    "683": "Hardware & household appliances",
    "684": "Furnishings & home workshops",
    "685": "Leather, fur, related products",
    "686": "Printing & related activities",
    "687": "Clothing",
    "688": "Other final products & packaging",
    "689": "Not assigned or no longer used",
    "690": "Buildings",
    "691": "Building materials",
    "692": "Auxiliary construction practices",
    "693": "Specific materials & purposes",
    "694": "Wood construction Carpentry",
    "695": "Roof covering",
    "696": "Utilities",
    "697": "Heating, ventilating, air-conditioning",
    "698": "Detail finishing",
    "699": "Not assigned or no longer used",
    "700": "The arts",
    "701": "Philosophy & theory",
    "702": "Miscellany",
    "703": "Dictionaries & encyclopedias",
    "704": "Special topics",
    "705": "Serial publications",
    "706": "Organizations & management",
    "707": "Education, research, related topics",
    "708": "Galleries, museums, private collections",
    "709": "Historical, areas, persons treatment",
    "710": "Civic & landscape art",
    "711": "Area planning (Civic art)",
    "712": "Landscape architecture",
    "713": "Landscape architecture of trafficways",
    "714": "Water features",
    "715": "Woody plants",
    "716": "Herbaceous plants",
    "717": "Structures",
    "718": "Landscape design of cemeteries",
    "719": "Natural landscapes",
    "720": "Architecture",
    "721": "Architectural structure",
    "722": "Architecture to ca. 300",
    "723": "Architecture from ca. 300 to 1399",
    "724": "Architecture from 1400",
    "725": "Public structures",
    "726": "Buildings for religious purposes",
    "727": "Buildings for education & research",
    "728": "Residential & related buildings",
    "729": "Design & decoration",
    "730": "Plastic arts Sculpture",
    "731": "Processes, forms, subjects of sculpture",
    "732": "Sculpture to ca. 500",
    "733": "Greek, Etruscan, Roman sculpture",
    "734": "Sculpture from ca. 500 to 1399",
    "735": "Sculpture from 1400",
    "736": "Carving & carvings",
    "737": "Numismatics & sigillography",
    "738": "Ceramic arts",
    "739": "Art metalwork",
    "740": "Drawing & decorative arts",
    "741": "Drawing & drawings",
    "742": "Perspective",
    "743": "Drawing & drawings by subject",
    "744": "Not assigned or no longer used",
    "745": "Decorative arts",
    "746": "Textile arts",
    "747": "Interior decoration",
    "748": "Glass",
    "749": "Furniture & accessories",
    "750": "Painting & paintings",
    "751": "Techniques, equipment, forms",
    "752": "Color",
    "753": "Symbolism, allegory, mythology, legend",
    "754": "Genre paintings",
    "755": "Religion & religious symbolism",
    "756": "Not assigned or no longer used",
    "757": "Human figures & their parts",
    "758": "Other subjects",
    "759": "Historical, areas, persons treatment",
    "760": "Graphic arts Printmaking & prints",
    "761": "Relief processes(Block printing)",
    "762": "Not assigned or no longer used",
    "763": "Lithographic (Planographic) processes",
    "764": "Chromolithography & serigraphy",
    "765": "Metal engraving",
    "766": "Mezzotinting & related processes",
    "767": "Etching & drypoint",
    "768": "Not assigned or no longer used",
    "769": "Prints",
    "770": "Photography & photographs",
    "771": "Techniques, equipment, materials",
    "772": "Metallic salt processes",
    "773": "Pigment processes of printing",
    "774": "Holography",
    "775": "Not assigned or no longer used",
    "776": "Not assigned or no longer used",
    "777": "Not assigned or no longer used",
    "778": "Fields & kinds of photography",
    "779": "Photographs",
    "780": "Music",
    "781": "General principles & musical forms",
    "782": "Vocal music",
    "783": "Music for single voices The voice",
    "784": "Instruments & Instrumental ensembles",
    "785": "Chamber music",
    "786": "Keyboard & other instruments",
    "787": "Stringed instruments (Chordophones)",
    "788": "Wind instruments (Aerophones)",
    "789": "Not assigned or no longer used",
    "790": "Recreational & performing arts",
    "791": "Public performances",
    "792": "Stage presentations",
    "793": "Indoor games & amusements",
    "794": "Indoor games of skill",
    "795": "Games of chance",
    "796": "Athletic & outdoor sports & games",
    "797": "Aquatic & air sports",
    "798": "Equestrian sports & animal racing",
    "799": "Fishing, hunting, shooting",
    "800": "Literature & rhetoric",
    "801": "Philosophy & theory",
    "802": "Miscellany",
    "803": "Dictionaries & encyclopedias",
    "804": "Not assigned or no longer used",
    "805": "Serial publications",
    "806": "Organizations",
    "807": "Education, research, related topics",
    "808": "Rhetoric & collections of literature",
    "809": "Literary history & criticism",
    "810": "American literature in English",
    "811": "Poetry",
    "812": "Drama",
    "813": "Fiction",
    "814": "Essays",
    "815": "Speeches",
    "816": "Letters",
    "817": "Satire & humor",
    "818": "Miscellaneous writings",
    "819": "Not used",
    "820": "English & Old English literatures",
    "821": "English poetry",
    "822": "English drama",
    "823": "English fiction",
    "824": "English essays",
    "825": "English speeches",
    "826": "English letters",
    "827": "English satire & humor",
    "828": "English miscellaneous writings",
    "829": "Old English (Anglo-Saxon)",
    "830": "Literatures of Germanic languages",
    "831": "Early to 1517",
    "832": "Reformation, etc. 1517-1750",
    "833": "Classic period, 1750-1830",
    "834": "Post classic & modern, 1830-1940/50",
    "835": "Contemporary authors not already established in the UIUC catalog, 1940/50-",
    "836": "German dialect literature",
    "837": "German-American",
    "838": "German miscellaneous writings",
    "839": "Other Germanic literatures",
    "840": "Literatures of Romance languages",
    "841": "Old and early French to 1400",
    "842": "Transition & renaissance periods, 1400-1600",
    "843": "Classical period, 1600-1715",
    "844": "18 th Century, 1715-1789",
    "845": "Revolution to present, 1789-1940/50",
    "846": "Contemporary authors not already established in the UIUC Catalog, 1940/50-",
    "847": "French Canadian",
    "848": "Provencal",
    "849": "French dialect literature",
    "850": "Italian, Romanian, Rhaeto-Romanic",
    "851": "Early period to 1375",
    "852": "Classical learning, 1375-1492",
    "853": "1492-1585",
    "854": "1585-1814",
    "855": "1814-1940/50",
    "856": "Works in and/or about Italian dialects",
    "857": "Sardinian",
    "858": "Romanian (including Wallachian)",
    "859": "Rumansh, Rhastian, Rhaeto-Romanic, Moldavian",
    "860": "Spanish & Portuguese literatures",
    "861": "Early to 1400",
    "862": "1400-1553",
    "863": "Golden age, 1554-1700",
    "864": "1700-1800",
    "865": "1800-",
    "866": "Works in and/or about Iberian dialects other than Castilian, Catalan and Portuguese, including Asturian/Bable, Aragonese, Navarrese, Ladino, Sephardic, Morisco, Aljamia",
    "867": "Catalan",
    "868": "Portuguese",
    "869": "South/Central American Literature",
    "870": "General works on Latin literature",
    "871": "Latin Authors",
    "872": "Collections of Latin prose or poetry",
    "873": "Not Used",
    "874": "Not Used",
    "875": "Medieval and modern Latin literature, 500 A.D. – date",
    "876": "Not Used",
    "877": "Not Used",
    "878": "Not Used",
    "879": "Classical literature-History and criticism",
    "880": "Hellenic literatures Classical Greek",
    "881": "Greek Authors",
    "882": "Collections of Greek prose or poetry",
    "883": "Not Used",
    "884": "Not Used",
    "885": "Modern Literature in the Ancient Greek Language",
    "886": "Not Used",
    "887": "Not Used",
    "888": "Not Used",
    "889": "Literature in Medieval and Modern Greek",
    "890": "Other literatures",
    "891.49": "Indic Literature",
    "891.5": "Iranian/Persian Literature",
    "891.6": "Celtic/Gaelic Literature",
    "891.7": "Slavic and Baltic Literatures",
    "892": "Afro-Asiatic Literature (Hamito-Semitic)",
    "893": "Non-Semitic Afro-Asiatic languages",
    "894": "Ural-Altaic, Paleosiberian, Dravidian",
    "895": "Languages of East & Southeast Asia",
    "896": "African languages",
    "897": "North American native languages",
    "898": "South American native languages",
    "899": "Miscellaneous languages",
    "900": "Geography & history",
    "901": "Philosophy & theory",
    "902": "Miscellany",
    "903": "Dictionaries & encyclopedias",
    "904": "Collected accounts of events",
    "905": "Serial publications",
    "906": "Organizations & management",
    "907": "Education, research, related topics",
    "908": "With respect to kinds of persons",
    "909": "World history",
    "910": "Geography & travel",
    "911": "Historical geography",
    "912": "Graphic representations of earth",
    "913": "Ancient world",
    "914": "Europe",
    "915": "Asia",
    "916": "Africa",
    "917": "North America",
    "918": "South America",
    "919": "Other areas",
    "920": "Biography, genealogy, insignia",
    "921": "Not assigned or no longer used",
    "922": "Not assigned or no longer used",
    "923": "Not assigned or no longer used",
    "924": "Not assigned or no longer used",
    "925": "Not assigned or no longer used",
    "926": "Not assigned or no longer used",
    "927": "Not assigned or no longer used",
    "928": "Not assigned or no longer used",
    "929": "Genealogy, names, insignia",
    "930": "History of ancient world",
    "931": "History of ancient world China",
    "932": "History of ancient world Egypt",
    "933": "History of ancient world Palestine",
    "934": "History of ancient world India",
    "935": "History of ancient world Mesopotamia & Iranian Plateau",
    "936": "History of ancient world Europe north & west of Italy",
    "937": "History of ancient world Italy & adjacent territories",
    "938": "History of ancient world Greece",
    "939": "History of ancient world Other parts of ancient world",
    "940": "General history of Europe",
    "941": "General history of Europe British Isles",
    "942": "General history of Europe England & Wales",
    "943": "General history of Europe Central Europe Germany",
    "944": "General history of Europe France & Monaco",
    "945": "General history of Europe Italian Peninsula & adjacent islands",
    "946": "General history of Europe Iberian Peninsula & adjacent islands",
    "947": "General history of Europe Eastern Europe Soviet Union",
    "948": "General history of Europe Northern Europe Scandinavia",
    "949": "General history of Europe Other parts of Europe",
    "950": "General history of Asia Far East",
    "951": "General history of Asia China & adjacent areas",
    "952": "General history of Asia Japan",
    "953": "General history of Asia Arabian Peninsula & adjacent areas",
    "954": "General history of Asia South Asia India",
    "955": "General history of Asia Iran",
    "956": "General history of Asia Middle East (Near East)",
    "957": "General history of Asia Siberia (Asiatic Russia)",
    "958": "General history of Asia Central Asia",
    "959": "General history of Asia Southeast Asia",
    "960": "General history of Africa",
    "961": "General history of Africa Tunisia & Libya",
    "962": "General history of Africa Egypt & Sudan",
    "963": "General history of Africa Ethiopia",
    "964": "General history of Africa Morocco & Canary Islands",
    "965": "General history of Africa Algeria",
    "966": "General history of Africa West Africa & offshore islands",
    "967": "General history of Africa Central Africa & offshore islands",
    "968": "General history of Africa Southern Africa",
    "969": "General history of Africa South Indian Ocean islands",
    "970": "General history of North America",
    "971": "General history of North America Canada",
    "972": "General history of North America Middle America Mexico",
    "973": "General history of North America United States",
    "973.7": "L63 Used for Abraham Lincoln works",
    "974": "General history of North America Northeastern United States",
    "975": "General history of North America Southeastern United States",
    "976": "General history of North America South central United States",
    "977": "General history of North America North central United States",
    "978": "General history of North America Western United States",
    "979": "General history of North America Great Basin & Pacific Slope",
    "980": "General history of South America",
    "981": "General history of South America Brazil",
    "982": "General history of South America Argentina",
    "983": "General history of South America Chile",
    "984": "General history of South America Bolivia",
    "985": "General history of South America Peru",
    "986": "General history of South America Colombia & Ecuador",
    "987": "General history of South America Venezuela",
    "988": "General history of South America Guiana",
    "989": "General history of South America Paraguay & Uruguay",
    "990": "General history of other areas",
    "991": "Not assigned or no longer used",
    "992": "Not assigned or no longer used",
    "993": "General history of other areas New Zealand",
    "994": "General history of other areas Australia",
    "995": "General history of other areas Melanesia New Guinea",
    "996": "General history of other areas Other parts of Pacific Polynesia",
    "997": "General history of other areas Atlantic Ocean islands",
    "998": "General history of other areas Arctic islands & Antarctica",
    "999": "Extraterrestrial worlds",
}


class TechnologyScienceDocumentMachineReadingComprehensionAITrainingDataset(GeneratorBasedBuilder):
    BUILDER_CONFIGS = [
        BuilderConfig(name="summerization", version=_VERSION),
        BuilderConfig(name="corpus", version=_VERSION),
    ]
    DEFAULT_CONFIG_NAME = "corpus"
    VERSION = _VERSION

    def _info(self) -> DatasetInfo:
        if self.config.name == "corpus":
            features = Features(
                {
                    "id": Value("int32"),
                    "corpus": Value("string"),
                    "category": Value("string"),
                    "sentence_ls": [Value("string")],
                    "metadata": {
                        "doc_category": {"KDC": Value("string"), "DDC": Value("string")},
                        "doc_title": {"kor": Value("string"), "eng": Value("string")},
                        "doc_type": Value("string"),
                        "doc_id": Value("string"),
                        "doc_number": {
                            "ISSN": Value("string"),
                            "ISBN": Value("string"),
                            "DOI": Value("string"),
                            "UCI": Value("string"),
                        },
                        "doc_year": Value("string"),
                        "doc_author": [Value("string")],
                        "doc_publisher": Value("string"),
                        "dataset_info": {
                            "identifier": Value("string"),
                            "name": Value("string"),
                            "category": Value("string"),
                            "last_updated": Value("string"),
                        },
                    },
                }
            )
        elif self.config.name == "summerization":
            features = Features(
                {
                    "id": Value("string"),
                    "context": Value("string"),
                    "question_answer": [
                        {
                            "id": Value("string"),
                            "question": Value("string"),
                            "answer": Value("string"),
                            "answer_start": Value("string"),
                            "answer_end": Value("string"),
                            "question_level": Value("string"),
                            "answer_type": Value("string"),
                            "question_type": Value("string"),
                            "question_ls": [Value("string")],
                            "clue": [
                                {
                                    "text": Value("string"),
                                    "start": Value("string"),
                                    "end": Value("string"),
                                }
                            ],
                        }
                    ],
                    "metadata": {
                        "context_length": Value("int32"),
                        "table_type": Value("int32"),
                        "context_K-NSCC": {
                            "field": Value("string"),
                            "large_category": Value("string"),
                            "medium_category": Value("string"),
                        },
                    },
                }
            )
        else:
            raise NotImplementedError(f"없는 config 임. {self.config.name}")

        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=features,
            supervised_keys=None,
            homepage=_HOMEPAGE,
            license=_LICENSE,
            citation=None,
        )

    def aihub_downloader(self, destination_path: Path) -> None:
        aihub_id = os.getenv("AIHUB_ID", None)
        aihub_pass = os.getenv("AIHUB_PASS", None)

        if not aihub_id:
            raise ValueError(
                """AIHUB_ID가 지정되지 않았습니다. `os.environ["AIHUB_ID"]="your_id"`로 ID를 지정해 주세요"""
            )
        if not aihub_pass:
            raise ValueError(
                """AIHUB_PASS가 지정되지 않았습니다. `os.environ["AIHUB_PASS"]="your_pass"`로 ID를 지정해 주세요"""
            )

        response = requests.get(
            DOWNLOAD_URL,
            headers={"id": aihub_id, "pass": aihub_pass},
            params={"fileSn": "all"},
            stream=True,
        )

        if response.status_code == 502:
            raise BaseException(
                "다운로드 서비스는 홈페이지(https://aihub.or.kr)에서 신청 및 승인 후 이용 가능 합니다."
            )
        elif response.status_code != 200:
            raise BaseException(f"Download failed with HTTP status code: {response.status_code}")

        data_file = open(destination_path, "wb")
        downloaded_bytes = 0
        with tqdm(total=round(DATASET_SIZE * 1024**2)) as pbar:
            for chunk in response.iter_content(chunk_size=1024):
                data_file.write(chunk)
                downloaded_bytes += len(chunk)

                pbar.update(1)
                prefix = f"Downloaded (GB): {downloaded_bytes / (1024**3):.4f}/{DATASET_SIZE}"
                pbar.set_postfix_str(prefix)

        data_file.close()

    def concat_zip_part(self, unzip_dir: Path) -> None:
        part_glob = Path(unzip_dir).rglob("*.zip.part*")

        part_dict = dict()
        for part_path in part_glob:
            parh_stem = str(part_path.parent.joinpath(part_path.stem))

            if parh_stem not in part_dict:
                part_dict[parh_stem] = list()

            part_dict[parh_stem].append(part_path)

        for dst_path, part_path_ls in part_dict.items():
            with open(dst_path, "wb") as byte_f:
                for part_path in natsorted(part_path_ls):
                    byte_f.write(part_path.read_bytes())
                    os.remove(part_path)

    def _split_generators(self, dl_manager) -> List[SplitGenerator]:  # type: ignore
        cache_dir = Path(dl_manager.download_config.cache_dir)

        unzip_dir = cache_dir.joinpath(_DATANAME)
        tar_file = cache_dir.joinpath(f"{_DATANAME}.tar")

        if tar_file.exists():
            os.remove(tar_file)

        if not unzip_dir.exists():
            self.aihub_downloader(tar_file)

            with TarFile(tar_file, "r") as mytar:
                mytar.extractall(unzip_dir)
                os.remove(tar_file)

            self.concat_zip_part(unzip_dir)

        zip_file_path = list(unzip_dir.rglob("*.zip"))

        train_split = [x for x in zip_file_path if "/01-1.정식개방데이터/Training" in str(x)]
        valid_split = [x for x in zip_file_path if "/01-1.정식개방데이터/Validation" in str(x)]

        return [
            SplitGenerator(
                name=Split.TRAIN,
                gen_kwargs={
                    "filepath": train_split,
                    "split": "train",
                },
            ),
            SplitGenerator(
                name=Split.VALIDATION,
                gen_kwargs={
                    "filepath": valid_split,
                    "split": "validation",
                },
            ),
        ]

    def _generate_summerization_example(self, label_ls):
        idx = 0
        for label_zip in label_ls:
            for file_info in label_zip.filelist:
                label_bytes = label_zip.open(file_info).read()
                label = json.loads(label_bytes.decode("utf-8"))
                for context_info in label["dataset"]["context_info"]:
                    question_answer_ls = list()
                    for question_answer in context_info["qas"]:
                        question_ls = [question_answer["question-1"], question_answer["question-2"]]
                        question_ls = [x for x in question_ls if x]

                        clue_ls = list()
                        for clue in question_answer["clue"]:
                            clue_ls.append(
                                {
                                    "text": clue["clue_text"],
                                    "start": clue["clue_start"],
                                    "end": clue["clue_end"],
                                }
                            )

                        label_dict = {
                            "id": question_answer["question_id"],
                            "question": random.choice(question_ls),
                            "answer": question_answer["answer"],
                            "answer_start": question_answer["answer_start"]
                            if "answer_start" in question_answer
                            else None,
                            "answer_end": question_answer["answer_end"] if "answer_end" in question_answer else None,
                            "question_level": question_answer["question_level"],
                            "answer_type": question_answer["answer_type"],
                            "question_type": question_answer["question_type"]
                            if "question_type" in question_answer
                            else None,
                            "question_ls": question_ls,
                            "clue": clue_ls,
                        }
                        question_answer_ls.append(label_dict)

                    data = {
                        "id": context_info["context_id"],
                        "context": context_info["context"],
                        "question_answer": question_answer_ls,
                        "metadata": {
                            "context_length": context_info["context_length"],
                            "table_type": context_info["table_type"],
                            "context_K-NSCC": context_info["context_K-NSCC"],
                        },
                    }
                    yield (idx, data)
                    idx += 1

    def _generate_corpus_example(self, label_ls):
        split_sentences = Kss("split_sentences")
        idx = 0
        for label_zip in label_ls:
            for file_info in label_zip.filelist:
                label_bytes = label_zip.open(file_info).read()
                label = json.loads(label_bytes.decode("utf-8"))
                corpus = " ".join([x["context"] for x in label["dataset"]["context_info"]])
                # 이유는 모르겠는데 `413.05` 이런 데이터가 종종 있음. 참고
                if label["dataset"]["doc_category"]["KDC"]:
                    KDC_category = kdc_dict[label["dataset"]["doc_category"]["KDC"].split(".")[0]]
                else:
                    KDC_category = ddc_dict[label["dataset"]["doc_category"]["DDC"].split(".")[0]]

                data = {
                    "id": idx,
                    "corpus": corpus,
                    "category": KDC_category,
                    "sentence_ls": split_sentences(corpus),
                    "metadata": {
                        "doc_category": label["dataset"]["doc_category"],
                        "doc_title": label["dataset"]["doc_title"],
                        "doc_type": label["dataset"]["doc_type"],
                        "doc_id": label["dataset"]["doc_id"],
                        "doc_number": label["dataset"]["doc_number"],
                        "doc_year": label["dataset"]["doc_year"],
                        "doc_author": label["dataset"]["doc_author"],
                        "doc_publisher": label["dataset"]["doc_publisher"],
                        "dataset_info": label["dataset_info"],
                    },
                }

                yield (idx, data)
                idx += 1

    def _generate_examples(self, filepath, split):
        label_ls = [ZipFile(x) for x in filepath if "라벨링데이터" in str(x)]

        if self.config.name == "corpus":
            return self._generate_corpus_example(label_ls)
        elif self.config.name == "summerization":
            return self._generate_summerization_example(label_ls)
